/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import exportImportKkm from "export-import-kkm/strapi-admin";
import strapiAdvancedUuid from "strapi-advanced-uuid/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "export-import-kkm": exportImportKkm,
    "strapi-advanced-uuid": strapiAdvancedUuid,
  },
});
